"""Tests for dark_factory.scaffold: Phases 3 and 4."""

from __future__ import annotations

import asyncio
from pathlib import Path
from unittest.mock import AsyncMock, patch

import pytest

from dark_factory.scaffold import (
    PlanReviewResult,
    ReviewFinding,
    ScaffoldResult,
    WorktreeInfo,
    _detect_package_manager,
    _ensure_gitignore,
    _parse_scaffold_output,
    _read_safe,
    create_worktree,
    run_phase_3,
    run_phase_4,
)
from dark_factory.state import PipelineState, SourceInfo


@pytest.fixture
def state(tmp_path):
    return PipelineState(
        source=SourceInfo(kind="jira", raw="TEST-1", id="test-1"),
        repo_root=str(tmp_path),
    )


# ---------------------------------------------------------------------------
# WorktreeInfo
# ---------------------------------------------------------------------------

class TestWorktreeInfo:
    def test_fields(self):
        info = WorktreeInfo(
            worktree_path="/tmp/wt",
            branch="dark-factory/test-1",
            change_id="dark-factory-test-1",
            repo_root="/repo",
        )
        assert info.branch == "dark-factory/test-1"
        assert info.change_id == "dark-factory-test-1"


# ---------------------------------------------------------------------------
# Package manager detection
# ---------------------------------------------------------------------------

class TestDetectPackageManager:
    def test_pnpm(self, tmp_path):
        (tmp_path / "pnpm-lock.yaml").write_text("")
        assert _detect_package_manager(str(tmp_path)) == "pnpm"

    def test_yarn(self, tmp_path):
        (tmp_path / "yarn.lock").write_text("")
        assert _detect_package_manager(str(tmp_path)) == "yarn"

    def test_npm_lock(self, tmp_path):
        (tmp_path / "package-lock.json").write_text("")
        assert _detect_package_manager(str(tmp_path)) == "npm"

    def test_npm_fallback(self, tmp_path):
        (tmp_path / "package.json").write_text("{}")
        assert _detect_package_manager(str(tmp_path)) == "npm"

    def test_no_package_manager(self, tmp_path):
        assert _detect_package_manager(str(tmp_path)) is None


# ---------------------------------------------------------------------------
# Gitignore helper
# ---------------------------------------------------------------------------

class TestEnsureGitignore:
    def test_creates_entry(self, tmp_path):
        _ensure_gitignore(str(tmp_path))
        content = (tmp_path / ".gitignore").read_text()
        assert ".dark-factory/" in content

    def test_idempotent(self, tmp_path):
        _ensure_gitignore(str(tmp_path))
        _ensure_gitignore(str(tmp_path))
        content = (tmp_path / ".gitignore").read_text()
        assert content.count(".dark-factory/") == 1

    def test_appends_to_existing(self, tmp_path):
        (tmp_path / ".gitignore").write_text("node_modules/\n")
        _ensure_gitignore(str(tmp_path))
        content = (tmp_path / ".gitignore").read_text()
        assert "node_modules/" in content
        assert ".dark-factory/" in content


# ---------------------------------------------------------------------------
# Scaffold output parsing
# ---------------------------------------------------------------------------

class TestParseScaffoldOutput:
    def test_with_delimiters(self):
        text = (
            "=== FILE: proposal.md ===\n"
            "# My Proposal\n\nWhy we need this.\n\n"
            "=== FILE: spec.md ===\n"
            "# Spec\n\n## Requirements\n\n"
            "=== FILE: tasks.md ===\n"
            "1. First task\n2. Second task\n"
        )
        files = _parse_scaffold_output(text)
        assert "proposal.md" in files
        assert "spec.md" in files
        assert "tasks.md" in files
        assert "My Proposal" in files["proposal.md"]
        assert "First task" in files["tasks.md"]

    def test_missing_files_get_placeholders(self):
        text = "=== FILE: proposal.md ===\n# Proposal\n"
        files = _parse_scaffold_output(text)
        assert "proposal.md" in files
        assert "spec.md" in files
        assert "tasks.md" in files
        # Missing files get placeholder content
        assert "Generated by Dark Factory" in files["spec.md"]

    def test_empty_input(self):
        files = _parse_scaffold_output("")
        assert len(files) == 3
        for name in ("proposal.md", "spec.md", "tasks.md"):
            assert name in files

    def test_path_in_filename(self):
        text = (
            "=== FILE: specs/main/spec.md ===\n"
            "# Spec content\n\n"
            "=== FILE: proposal.md ===\n"
            "# Proposal content\n\n"
            "=== FILE: tasks.md ===\n"
            "# Tasks content\n"
        )
        files = _parse_scaffold_output(text)
        assert "spec.md" in files
        assert "Spec content" in files["spec.md"]


# ---------------------------------------------------------------------------
# create_worktree (dry-run only)
# ---------------------------------------------------------------------------

class TestCreateWorktree:
    def test_dry_run_returns_info(self, tmp_path):
        info = create_worktree(str(tmp_path), "test-1", dry_run=True)
        assert info.branch == "dark-factory/test-1"
        assert info.change_id == "dark-factory-test-1"
        assert info.repo_root == str(tmp_path)
        assert "df-test-1" in info.worktree_path


# ---------------------------------------------------------------------------
# Phase 3 (dry-run)
# ---------------------------------------------------------------------------

class TestPhase3DryRun:
    def test_returns_scaffold_result(self, state):
        with patch(
            "dark_factory.agents._sdk_query",
            new_callable=AsyncMock,
            return_value=(["=== FILE: proposal.md ===\n# P\n=== FILE: spec.md ===\n# S\n=== FILE: tasks.md ===\n# T"], 0.0, 0),
        ):
            result = asyncio.run(run_phase_3(
                state,
                source_id_lower="test-1",
                summary="Test feature",
                description="A test feature description",
                acceptance_criteria=["AC-1", "AC-2"],
                external_ref="jira:TEST-1",
                dry_run=True,
            ))
        assert isinstance(result, ScaffoldResult)
        assert result.worktree.branch == "dark-factory/test-1"

    def test_sets_state_fields(self, state):
        with patch(
            "dark_factory.agents._sdk_query",
            new_callable=AsyncMock,
            return_value=(["placeholder"], 0.0, 0),
        ):
            asyncio.run(run_phase_3(
                state,
                source_id_lower="test-1",
                summary="s",
                description="d",
                acceptance_criteria=[],
                external_ref="jira:TEST-1",
                dry_run=True,
            ))
        assert state.branch == "dark-factory/test-1"
        assert "df-test-1" in state.worktree_path


# ---------------------------------------------------------------------------
# Phase 4 (dry-run)
# ---------------------------------------------------------------------------

class TestPhase4DryRun:
    def test_returns_plan_review_result(self, tmp_path):
        # Create openspec file structure
        change_dir = tmp_path / "openspec" / "changes" / "dark-factory-test-1"
        specs_dir = change_dir / "specs" / "main"
        specs_dir.mkdir(parents=True)
        (change_dir / "proposal.md").write_text("# Proposal")
        (specs_dir / "spec.md").write_text("# Spec\n## Req A")
        (change_dir / "tasks.md").write_text("1. Task A\n2. Task B")

        result = asyncio.run(run_phase_4(
            worktree_path=str(tmp_path),
            change_id="dark-factory-test-1",
            external_ref="jira:TEST-1",
            summary="Test feature",
            acceptance_criteria=["AC-1"],
            dry_run=True,
        ))
        assert isinstance(result, PlanReviewResult)
        assert result.verdict == "PASS"
        assert result.review_cost_usd == 0.0


# ---------------------------------------------------------------------------
# _read_safe
# ---------------------------------------------------------------------------

class TestReadSafe:
    def test_reads_existing_file(self, tmp_path):
        f = tmp_path / "test.txt"
        f.write_text("hello")
        assert _read_safe(f) == "hello"

    def test_returns_empty_for_missing(self, tmp_path):
        assert _read_safe(tmp_path / "nope.txt") == ""


# ---------------------------------------------------------------------------
# ReviewFinding
# ---------------------------------------------------------------------------

class TestReviewFinding:
    def test_fields(self):
        f = ReviewFinding(category="coverage", description="Missing AC-3")
        assert f.category == "coverage"


class TestPlanReviewResult:
    def test_default_verdict(self):
        r = PlanReviewResult()
        assert r.verdict == "PASS"

    def test_total_cost(self):
        r = PlanReviewResult(review_cost_usd=1.5)
        assert r.review_cost_usd == 1.5
